### ISSUE TITLE
count.points should use 'message' instead of 'cat'

### ISSUE THREAD

**Issue by basille** [ClementCalenge/adehabitatMA#1]
The subject says it all: `count.points` should use `message` instead of `cat` so that we can silence it with `suppressMessages`. Additionally, an option `verbose = TRUE` (which would be `TRUE` by default) would even allow to silence the function programmatically. This would be particularly useful when scripting `count.points` over many layers.

```
count.points <- function (xy, w, verbose = TRUE) 
{
    <...>
    else {
        if (verbose) 
            message("Counting the number of points for each level of the factor ", 
                names(xy@data)[1], "...")
        <...>
    }
    <...>
}
```

**Comment by ClementCalenge** [comment]
Ooops, forgot to close the issue. Never mind, it's never too late.

**Comment by basille** [comment]
Just curious, when did the fix happen? 😃

**Comment by ClementCalenge** [comment]
It was fixed on Nov 16, 2016 !
(see https://github.com/ClementCalenge/adehabitatMA/commit/b9385725b878f1cf260a5d8d88e079bd76fe3912)

**Comment by basille** [comment]
Niiiice!
